spring:
  application:
    name: booking-service
  profiles:
    active: dev
    boot:
    admin:
      client:
        url: http://localhost:9020
        username: admin
        password: admin
        instance:
          service-base-url: http://localhost:9050
          name: Booking API Service
          metadata:
            user.name: admin
            user.password: admin
server:
  servlet:
    context-path: /bookings
  port: 9050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always