spring:
  application:
    name: booking-service
  profiles:
    active: dev
server:
  servlet:
    context-path: /bookings
  port: 9050
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
