server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/users/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: showtime-service
          uri: lb://showtime-service
          predicates:
            - Path=/showtime/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
