spring:
  application:
    name: movie-service
  profiles:
    active: dev
server:
  servlet:
    context-path: /movies
  port: 9070
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/

