spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: "jdbc:h2:mem:showtime;"
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  boot:
    admin:
      client:
        url: http://localhost:9020
        username: admin
        password: admin
        instance:
          service-base-url: http://localhost:9080
          name: Showtime API Service
          metadata:
            user.name: admin
            user.password: admin
server:
  servlet:
    context-path: /showtime
  port: 9080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
feign:
  circuitbreaker:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always