spring:
  application:
    name: user-service
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:9020
        username: admin
        password: admin
        instance:
          service-base-url: http://localhost:9060
          name: User API Service
          metadata:
            user.name: admin
            user.password: admin
server:
  servlet:
    context-path: /users
  port: 9060
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
feign:
  circuitbreaker:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always