spring:
  application:
    name: customer-service
  profiles:
    active: dev
server:
  servlet:
    context-path: /store/api/v1
  port: 9060
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/